[package]
name = "astral-ini"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
description = "A high-performance INI parser designed for Python packaging"

[features]
benchmark-jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
indexmap.workspace = true
memchr.workspace = true

[dev-dependencies]
configparser.workspace = true
serde.workspace = true
serde_json.workspace = true
stats_alloc.workspace = true

[target.'cfg(all(target_os = "linux", any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
tikv-jemallocator = { version = "0.6.0", default-features = false, features = ["background_threads_runtime_support"], optional = true }

[lints]
workspace = true

[[bench]]
name = "parse"
harness = false
