//! Differential cases generated by CPython 3.12.

use astral_ini::{Delimiters, ErrorKind, Options};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    input: String,
    case_sensitive: bool,
    delimiters: String,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum Expected {
    Error {
        error: ExpectedError,
    },
    Parsed {
        defaults: Vec<(String, String)>,
        sections: Vec<(String, Vec<(String, String)>)>,
    },
}

#[derive(Debug, Deserialize)]
struct ExpectedError {
    kind: String,
    line: usize,
}

#[test]
fn python_conformance() {
    let fixtures: Fixtures = serde_json::from_str(include_str!("fixtures/python.json")).unwrap();
    for case in fixtures.cases {
        let context = format!(
            "{} (case_sensitive={}, delimiters={})",
            case.name, case.case_sensitive, case.delimiters
        );
        let options = Options::default()
            .case_sensitive(case.case_sensitive)
            .delimiters(if case.delimiters == "=" {
                Delimiters::Equals
            } else {
                Delimiters::EqualsAndColon
            });
        match (options.parse(&case.input), case.expected) {
            (Ok(ini), Expected::Parsed { defaults, sections }) => {
                assert_eq!(
                    ini.defaults().collect::<Vec<_>>(),
                    pairs(&defaults),
                    "{context}: defaults"
                );
                assert_eq!(
                    ini.sections().map(|(name, _)| name).collect::<Vec<_>>(),
                    sections.iter().map(|(name, _)| name).collect::<Vec<_>>(),
                    "{context}: section order"
                );
                for ((name, section), (_, expected)) in ini.sections().zip(&sections) {
                    assert_eq!(
                        section.iter().collect::<Vec<_>>(),
                        pairs(expected),
                        "{context}: section {name:?}"
                    );
                    let lookup = ini.section(name).expect("iterated section must exist");
                    assert_eq!(
                        lookup.iter().collect::<Vec<_>>(),
                        pairs(expected),
                        "{context}: section lookup {name:?}"
                    );
                    for (key, value) in expected {
                        assert_eq!(
                            section.get(key),
                            Some(value.as_str()),
                            "{context}: section lookup {name:?}/{key:?}"
                        );
                        assert_eq!(
                            ini.get(name, key),
                            Some(value.as_str()),
                            "{context}: document lookup {name:?}/{key:?}"
                        );
                    }
                }
                for (key, value) in defaults {
                    assert_eq!(
                        ini.get("DEFAULT", &key),
                        Some(value.as_str()),
                        "{context}: default lookup {key:?}"
                    );
                }
            }
            (Err(error), Expected::Error { error: expected }) => {
                let expected_kind = match expected.kind.as_str() {
                    "MissingSection" => ErrorKind::MissingSection,
                    "DuplicateSection" => ErrorKind::DuplicateSection,
                    "DuplicateOption" => ErrorKind::DuplicateOption,
                    "InvalidLine" => ErrorKind::InvalidLine,
                    other => panic!("unknown Python error category: {other}"),
                };
                assert_eq!(error.kind(), expected_kind, "{context}");
                assert_eq!(error.line(), expected.line, "{context}");
            }
            (Ok(_), expected) => panic!("{context}: accepted input, expected {expected:?}"),
            (Err(error), expected) => {
                panic!("{context}: rejected input with {error:?}, expected {expected:?}");
            }
        }
    }
}

fn pairs(values: &[(String, String)]) -> Vec<(&str, &str)> {
    values
        .iter()
        .map(|(key, value)| (key.as_str(), value.as_str()))
        .collect()
}

#[test]
fn lookup_uses_the_same_unicode_transform_as_parsing() {
    let source = "[DEFAULT]\nİ=default\n[Mixed]\nΟΣ=final\nΟσ=non-final\n[empty]\n";
    let ini = Options::default().parse(source).unwrap();
    for (section, key, expected) in [
        ("Mixed", "İ", Some("default")),
        ("Mixed", "i\u{307}", Some("default")),
        ("Mixed", "I", None),
        ("Mixed", "ΟΣ", Some("final")),
        ("Mixed", "ος", Some("final")),
        ("Mixed", "οσ", Some("non-final")),
        ("Mixed", "Οσ", Some("non-final")),
        ("Mixed", " ΟΣ ", None),
        ("empty", "İ", Some("default")),
        ("DEFAULT", "İ", Some("default")),
        ("mixed", "İ", None),
        ("missing", "İ", None),
    ] {
        assert_eq!(ini.get(section, key), expected, "{section}/{key}");
    }
    let sensitive = Options::default()
        .case_sensitive(true)
        .parse(source)
        .unwrap();
    assert_eq!(sensitive.get("Mixed", "ΟΣ"), Some("final"));
    assert_eq!(sensitive.get("Mixed", "ος"), None);
    assert_eq!(sensitive.get("Mixed", "i\u{307}"), None);
}

#[test]
fn empty_document_has_only_the_default_view() {
    let ini = Options::default().parse("").unwrap();
    assert_eq!(ini.sections().count(), 0);
    assert_eq!(ini.defaults().count(), 0);
    assert_eq!(ini.section("DEFAULT").unwrap().iter().count(), 0);
    assert!(ini.section("default").is_none());
    assert_eq!(ini.get("DEFAULT", "missing"), None);
}
