#!/usr/bin/env python3
"""Generate the Unicode 15 lowercase data used by CPython 3.12."""

import argparse
from pathlib import Path
import unicodedata

OUTPUT = Path(__file__).resolve().parents[1] / "crates/astral-ini/src/unicode_data.rs"


def ranges(values):
    result = []
    for value in values:
        if result and result[-1][1] + 1 == value:
            result[-1] = result[-1][0], value
        else:
            result.append((value, value))
    return result


def generate():
    if unicodedata.unidata_version != "15.0.0":
        raise SystemExit("Run this generator with CPython 3.12 (Unicode 15.0.0)")
    lower = []
    cased = []
    ignorable = []
    for codepoint in range(0x110000):
        if 0xD800 <= codepoint <= 0xDFFF:
            continue
        char = chr(codepoint)
        value = char.lower()
        if value != char and codepoint >= 128:
            if len(value) != 1:
                assert char == "\u0130" and value == "i\u0307"
            else:
                lower.append((codepoint, ord(value) - codepoint))
        is_cased = char.islower() or char.isupper() or char.istitle()
        if is_cased:
            cased.append(codepoint)
            # An ignorable cased character cannot supply the preceding case
            # needed to make the sigma final.
            is_ignorable = (" " + char + "\u03a3").lower().endswith("\u03c3")
        else:
            # An ignorable uncased character cannot hide the following letter
            # that prevents the sigma from being final.
            is_ignorable = ("A\u03a3" + char + "A").lower()[1] == "\u03c3"
        if is_ignorable:
            ignorable.append(codepoint)

    lower_ranges = []
    index = 0
    while index < len(lower):
        start, offset = lower[index]
        end = start
        step = 1
        if index + 1 < len(lower):
            next_value, next_offset = lower[index + 1]
            if next_offset == offset and next_value - start in (1, 2):
                step = next_value - start
                while index + 1 < len(lower) and lower[index + 1] == (end + step, offset):
                    index += 1
                    end += step
        lower_ranges.append((start, end, step, offset))
        index += 1

    lines = [
        "// Generated by scripts/generate_unicode.py from CPython 3.12 / Unicode 15.0.0.",
        "// Do not edit by hand.",
        "",
        "pub(super) const LOWERCASE: &[(u32, u32, u32, i32)] = &[",
    ]
    lines.extend(f"    (0x{start:X}, 0x{end:X}, {step}, {offset})," for start, end, step, offset in lower_ranges)
    lines.append("];")
    for name, values in (("CASED", cased), ("CASE_IGNORABLE", ignorable)):
        lines.extend(("", f"pub(super) const {name}: &[(u32, u32)] = &["))
        lines.extend(f"    (0x{start:X}, 0x{end:X})," for start, end in ranges(values))
        lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    source = generate()
    if arguments.check:
        if OUTPUT.read_text() != source:
            raise SystemExit("Unicode data differs; regenerate with CPython 3.12")
        print("Checked Unicode 15.0.0 lowercase data")
    else:
        OUTPUT.write_text(source)
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
